application: blaine-garrett
version: v20131229-stable
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: "1.2"
- name: PIL
  version: "1.1.7"

skip_files: |
   ^(.*/)?(
   (app\.yaml)|
   (app\.yml)|
   (index\.yaml)|
   (index\.yml)|
   (#.*#)|
   (.*~)|
   (.*\.py[co])|
   (.git/.*)|
   (.gitignore)|
   (.DS_Store)|
   (^docs/.*)|
   )$

env_variables:
   DJANGO_SETTINGS_MODULE: 'settings'

builtins:
  - remote_api: on
  - deferred: on

includes:
  - merkabah/merkabah.yaml

handlers:
- url: /static
  static_dir: static
  secure: optional

- url: /merkabah/static
  static_dir: merkabah/static
  secure: optional

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/themes/v2/assets/favicon.ico
  upload: static/themes/v2/assets/favicon\.ico

- url: .*
  script: main.py